name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Fluidize.csproj

      - name: Build application
        run: dotnet build Fluidize.csproj --configuration Release --no-restore

      - name: Check build status
        run: dotnet build Fluidize.csproj --configuration Release --no-restore --no-incremental
